<?php
/**
 * PRO-BUD: Shared project data.
 *
 * @package ProBud
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function probud_get_projects() {
	return array(
		'osiedle-parkowe-wilanow' => array(
			'slug'     => 'osiedle-parkowe-wilanow',
			'image'    => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Budownictwo mieszkaniowe',
			'title'    => 'Osiedle Parkowe Wilanów',
			'meta'     => '48 mieszkań · 2023',
			'location' => 'Warszawa, Wilanów',
			'area'     => '12 500 m²',
			'duration' => '18 miesięcy',
			'year'     => '2023',
			'desc'     => 'Nowoczesne osiedle z 48 mieszkaniami w standardzie premium. Realizacja obejmowała pełne wykończenie części wspólnych, zagospodarowanie terenu z placem zabaw i strefą relaksu.',
			'full_desc' => 'Osiedle Parkowe Wilanów to nasz flagowy projekt mieszkaniowy zrealizowany w prestiżowej dzielnicy Warszawy. Kompleks składa się z trzech budynków wielorodzinnych o nowoczesnej architekturze, doskonale wpisujących się w otoczenie. Realizacja obejmowała budowę od fundamentów po pełne wykończenie. Zastosowaliśmy energooszczędne rozwiązania: pompy ciepła, rekuperację, panele fotowoltaiczne. Części wspólne wykończone w podwyższonym standardzie — lobby z recepcją, podziemne garaże z ładowarkami EV, zagospodarowany teren zielony z placem zabaw, siłownią plenerową i strefą relaksu.',
			'scope'    => array( 'Projekt architektoniczny', 'Budowa stanu surowego', 'Instalacje sanitarne i elektryczne', 'Wykończenie pod klucz', 'Zagospodarowanie terenu', 'Odbiory i certyfikacja' ),
		),
		'biurowiec-nova-office' => array(
			'slug'     => 'biurowiec-nova-office',
			'image'    => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Obiekty komercyjne',
			'title'    => 'Biurowiec Nova Office',
			'meta'     => '12 000 m² · 2023',
			'location' => 'Warszawa, Mokotów',
			'area'     => '12 000 m²',
			'duration' => '24 miesiące',
			'year'     => '2023',
			'desc'     => 'Wielokondygnacyjny biurowiec klasy A z certyfikatem BREEAM. Nowoczesne rozwiązania energooszczędne, 3 poziomy garażu podziemnego.',
			'full_desc' => 'Nova Office to nowoczesny biurowiec klasy A zlokalizowany w biznesowym sercu Mokotowa. Budynek o 8 kondygnacjach naziemnych i 3 podziemnych oferuje elastyczne przestrzenie biurowe najwyższej jakości. Projekt uzyskał certyfikat BREEAM Excellent dzięki zastosowaniu zaawansowanych rozwiązań proekologicznych. Fasada z przeszkleniami o niskim współczynniku przenikania ciepła, system BMS zarządzający klimatyzacją i oświetleniem, zielony dach z retencją wody deszczowej. Garaż podziemny wyposażony w stacje ładowania pojazdów elektrycznych.',
			'scope'    => array( 'Generalny wykonawca', 'Konstrukcja żelbetowa', 'Fasada aluminiowo-szklana', 'Instalacje HVAC', 'System BMS', 'Certyfikacja BREEAM' ),
		),
		'rewitalizacja-kamienicy' => array(
			'slug'     => 'rewitalizacja-kamienicy',
			'image'    => 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Modernizacja',
			'title'    => 'Rewitalizacja Kamienicy',
			'meta'     => 'Zabytek · 2022',
			'location' => 'Warszawa, Śródmieście',
			'area'     => '2 800 m²',
			'duration' => '14 miesięcy',
			'year'     => '2022',
			'desc'     => 'Kompleksowa rewitalizacja zabytkowej kamienicy z XIX wieku. Odrestaurowanie fasady, wymiana instalacji, adaptacja poddasza na lokale mieszkalne.',
			'full_desc' => 'Rewitalizacja zabytkowej kamienicy z 1890 roku w ścisłym centrum Warszawy była jednym z najbardziej wymagających projektów w naszym portfolio. Prace prowadzono pod nadzorem konserwatora zabytków, z zachowaniem oryginalnych elementów architektonicznych — sztukaterii, klatki schodowej i detali fasady. Wymieniono wszystkie instalacje, wzmocniono stropy, wykonano izolację przeciwwilgociową fundamentów. Poddasze zaadaptowano na dwa ekskluzywne lofty mieszkalne z panoramicznym widokiem na miasto.',
			'scope'    => array( 'Nadzór konserwatorski', 'Wzmocnienie konstrukcji', 'Odrestaurowanie fasady', 'Wymiana instalacji', 'Adaptacja poddasza', 'Zagospodarowanie podwórza' ),
		),
		'centrum-logistyczne-pruszkow' => array(
			'slug'     => 'centrum-logistyczne-pruszkow',
			'image'    => 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1504615755583-2916b52192a3?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Infrastruktura',
			'title'    => 'Centrum Logistyczne Pruszków',
			'meta'     => '25 000 m² · 2022',
			'location' => 'Pruszków, woj. mazowieckie',
			'area'     => '25 000 m²',
			'duration' => '12 miesięcy',
			'year'     => '2022',
			'desc'     => 'Hala magazynowa z zapleczem biurowym i infrastrukturą drogową. Konstrukcja stalowa, posadzka przemysłowa, system automatyki budynkowej BMS.',
			'full_desc' => 'Centrum Logistyczne w Pruszkowie to nowoczesny obiekt magazynowo-biurowy o powierzchni 25 000 m². Hala o konstrukcji stalowej z wysokością składowania 12 metrów, posadzka przemysłowa utwardzona o nośności 5 ton/m². Zaplecze biurowe na dwóch kondygnacjach z pełnym wyposażeniem. Infrastruktura obejmuje drogi wewnętrzne, place manewrowe dla TIR, parking dla 200 samochodów osobowych, oświetlenie LED z czujnikami ruchu.',
			'scope'    => array( 'Konstrukcja stalowa hali', 'Posadzka przemysłowa', 'Zaplecze biurowe', 'Instalacje p.poż.', 'Drogi i place manewrowe', 'System BMS' ),
		),
		'rezydencja-pod-lasem' => array(
			'slug'     => 'rezydencja-pod-lasem',
			'image'    => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Budownictwo mieszkaniowe',
			'title'    => 'Rezydencja Pod Lasem',
			'meta'     => 'Dom jednorodzinny · 2023',
			'location' => 'Konstancin-Jeziorna',
			'area'     => '420 m²',
			'duration' => '16 miesięcy',
			'year'     => '2023',
			'desc'     => 'Ekskluzywna rezydencja o powierzchni 420 m² z basenem i garażem na 3 samochody. Wykończenie pod klucz z systemem inteligentnego domu.',
			'full_desc' => 'Rezydencja Pod Lasem to ekskluzywny dom jednorodzinny w Konstancinie-Jeziornej, zaprojektowany z myślą o najwyższym komforcie. Budynek o powierzchni 420 m² na działce 2000 m², z basenem krytym, garażem na 3 samochody i tarasem 80 m². Zastosowano system inteligentnego domu KNX sterujący ogrzewaniem, oświetleniem, roletami i alarmem. Wykończenie w standardzie premium — kamień naturalny, drewno dębowe, schody ze szkłem hartowanym.',
			'scope'    => array( 'Projekt indywidualny', 'Budowa stanu surowego', 'Wykończenie premium', 'Basen kryty', 'System smart home KNX', 'Zagospodarowanie ogrodu' ),
		),
		'hala-sportowa-ursynow' => array(
			'slug'     => 'hala-sportowa-ursynow',
			'image'    => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Obiekty komercyjne',
			'title'    => 'Hala Sportowa Ursynów',
			'meta'     => '5 200 m² · 2021',
			'location' => 'Warszawa, Ursynów',
			'area'     => '5 200 m²',
			'duration' => '14 miesięcy',
			'year'     => '2021',
			'desc'     => 'Wielofunkcyjna hala sportowa z widownią na 800 osób. Boisko wielofunkcyjne, 2 sale treningowe, zaplecze sanitarne i administracyjne.',
			'full_desc' => 'Hala Sportowa na Ursynowie to obiekt użyteczności publicznej zrealizowany na zlecenie gminy. Wielofunkcyjna hala główna z widownią teleskopową na 800 miejsc, boisko do koszykówki, siatkówki i piłki ręcznej. Dwie sale treningowe, siłownia, szatnie z natryskami, zaplecze administracyjne i medyczne. Konstrukcja z drewna klejonego — ekologiczna i estetyczna. Instalacja fotowoltaiczna 50 kWp na dachu.',
			'scope'    => array( 'Generalny wykonawca', 'Konstrukcja z drewna klejonego', 'Podłoga sportowa', 'Widownia teleskopowa', 'Instalacja fotowoltaiczna', 'Zagospodarowanie terenu' ),
		),
		'apartamenty-nadmorskie' => array(
			'slug'     => 'apartamenty-nadmorskie',
			'image'    => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Budownictwo mieszkaniowe',
			'title'    => 'Apartamenty Nadmorskie',
			'meta'     => '32 apartamenty · 2021',
			'location' => 'Sopot',
			'area'     => '4 200 m²',
			'duration' => '20 miesięcy',
			'year'     => '2021',
			'desc'     => 'Kameralny budynek z 32 apartamentami w nadmorskiej lokalizacji. Wykończenie w podwyższonym standardzie z panoramicznymi oknami.',
			'full_desc' => 'Apartamenty Nadmorskie to kameralny budynek w Sopocie, zaledwie 300 metrów od plaży. 32 apartamenty o powierzchniach 35–120 m² z panoramicznymi oknami od podłogi do sufitu. Każdy apartament z balkonem lub tarasem z widokiem na morze lub park. Wykończenie premium — podłogi dębowe, łazienki w kamieniu naturalnym. Części wspólne: lobby z recepcją, fitness, sauna, podziemny garaż.',
			'scope'    => array( 'Budowa od fundamentów', 'Konstrukcja żelbetowa', 'Fasada wentylowana', 'Wykończenie premium', 'Lobby i części wspólne', 'Garaż podziemny' ),
		),
		'wezel-drogowy-s7' => array(
			'slug'     => 'wezel-drogowy-s7',
			'image'    => 'https://images.unsplash.com/photo-1504615755583-2916b52192a3?w=800&h=600&fit=crop&q=80',
			'gallery'  => array(
				'https://images.unsplash.com/photo-1504615755583-2916b52192a3?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=800&fit=crop&q=80',
				'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=800&fit=crop&q=80',
			),
			'category' => 'Infrastruktura',
			'title'    => 'Węzeł drogowy S7',
			'meta'     => '2,5 km · 2020',
			'location' => 'Grójec, woj. mazowieckie',
			'area'     => '2,5 km trasy',
			'duration' => '10 miesięcy',
			'year'     => '2020',
			'desc'     => 'Budowa węzła drogowego z rondami, pasami włączeniowymi i oświetleniem drogowym. Odwodnienie i przebudowa sieci uzbrojenia.',
			'full_desc' => 'Węzeł drogowy przy trasie S7 koło Grójca to projekt infrastrukturalny zrealizowany dla GDDKiA. Zakres obejmował budowę dwóch rond turbinowych, pasów włączeniowych i wyłączeniowych, 2,5 km dróg dojazdowych z nawierzchnią asfaltową. Wykonano kompletne odwodnienie z separatorami, oświetlenie drogowe LED, przebudowano kolidujące sieci: wodociąg, kanalizacja, telekomunikacja. Prace realizowano przy utrzymaniu ruchu na istniejącej drodze.',
			'scope'    => array( 'Roboty ziemne', 'Nawierzchnia asfaltowa', 'Ronda turbinowe', 'Odwodnienie i kanalizacja', 'Oświetlenie drogowe', 'Przebudowa sieci' ),
		),
	);
}
